Issue #580: Remove excludes warning from diff.groovy report
checkstyle/contribution pull request #581
Opened 2021-11-15 21:58 UTC by nmancus1

Closes #580

2021-11-15 22:18 UTC, rnveach requested changes
See issue.

2021-12-05 15:20 UTC, romani commented
See issue comment

2021-12-20 02:33 UTC, romani approved these changes
Ok to merge

2021-12-20 15:43 UTC, rnveach approved these changes

2021-12-20 15:43 UTC, merged