Issue #634: satelite projects should use latest checkstyle as soon at is appears in maven repo
checkstyle/contribution pull request #636
Opened 2022-08-19 14:11 UTC by Rahulkhinchi03

Partially Fixes #634

2022-08-20 23:31 UTC, romani requested changes
item:

2022-08-20 23:31 UTC, romani commented on .ci/bump-patch-tool-version.sh
> +set -e
apply comments from https://github.com/checkstyle/contribution/pull/635#pullrequestreview-1079599409

2022-08-21 11:54 UTC, Rahulkhinchi03 commented on .ci/bump-patch-tool-version.sh
> +set -e
Changes Done

2022-08-21 12:49 UTC, romani approved these changes
ok to merge

2022-08-21 12:49 UTC, merged