Issue #614: Resolve CallToSystemExit, string formatting and string builder IDEA violations
checkstyle/contribution pull request #644
Opened 2022-08-27 13:44 UTC by Vyom-Yadav

#614

2022-08-27 19:18 UTC, romani requested changes
items:

2022-08-27 19:18 UTC, romani commented on releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
> +     * @noinspectionreason CallToSystemExit - driver class must call exit
`- main method must exist with code`

2022-08-27 20:25 UTC, Vyom-Yadav commented on releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
> +     * @noinspectionreason CallToSystemExit - driver class must call exit
Done.

2022-08-27 21:24 UTC, romani approved these changes
Ok to merge

2022-08-28 15:15 UTC, nick-mancuso approved these changes

2022-08-28 15:15 UTC, nick-mancuso commented
@Vyom-Yadav please resolve conflicts

2022-08-29 03:40 UTC, Vyom-Yadav commented
> @Vyom-Yadav please resolve conflicts

Done.

2022-08-29 11:32 UTC, merged