Issue #661: expands regression for VariableDeclarationUsageDistance
checkstyle/contribution pull request #754
Opened 2023-01-01 19:24 UTC by rnveach

Issue #661

2023-01-02 05:35 UTC, romani approved these changes

2023-01-02 15:15 UTC, nrmancuso requested changes
We need to create a PR in the main repo (and anywhere else this config is used) that uses this PR branch of contribution and make sure that we do not have failing CI there:
```
➜  checkstyle git:(master) ag -Q "checks-nonjavadoc-error.xml" --hidden
.ci/no-exception-test.sh
57:        .ci-temp/contribution/checkstyle-tester/checks-nonjavadoc-error.xml
62:      checks-nonjavadoc-error.xml
66:      --patchConfig checks-nonjavadoc-error.xml \
79:        .ci-temp/contribution/checkstyle-tester/checks-nonjavadoc-error.xml
84:      checks-nonjavadoc-error.xml
88:      --patchConfig checks-nonjavadoc-error.xml \

.ci/validation.sh
325:    https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/checks-nonjavadoc-error.xml
332:    -n $working_dir/checks-nonjavadoc-error.xml \
362:        echo '   to file checkstyle-tester/checks-nonjavadoc-error.xml'
371:      echo 'https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/checks-nonjavadoc-error.xml'
816:      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../..  \
834:      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../..  \
867:      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../..  \
882:      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../..  \
897:      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../..  \
912:      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../..  \
927:      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../..  \
942:      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../..  \
959:      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../..  \
979:      --patchConfig checks-nonjavadoc-error.xml  -p "$BRANCH" -r ../../.. \


```

2023-01-03 02:54 UTC, rnveach commented
> We need to create a PR in the main repo 

If it wasn't clear, this is done.

2023-01-03 04:41 UTC, nrmancuso approved these changes

2023-01-03 04:41 UTC, merged