minor: change config of MagicNumberCheck
checkstyle/contribution pull request #857
Opened 2024-04-22 04:12 UTC by Lmh-java

For https://github.com/checkstyle/checkstyle/pull/14791.

Added property for MagicNumberCheck to detect regression.

2024-04-22 15:41 UTC, rnveach requested changes

2024-04-22 15:41 UTC, rnveach commented on checkstyle-tester/checks-nonjavadoc-error.xml
> +    <module name="MagicNumber">
No, we need both. The other has the value of `false` correct? They will be testing different things then.

2024-04-22 19:32 UTC, rnveach approved these changes

2024-04-22 19:33 UTC, rnveach commented
This is blocked until https://github.com/checkstyle/checkstyle/pull/14791 is merged. We don't want to risk finding an NPE in regression while waiting for the PR to fix it to be merged.

2024-04-23 01:44 UTC, romani approved these changes

2024-04-24 16:45 UTC, rnveach commented
Blocked was removed as PR was merged.

2024-04-25 02:23 UTC, nrmancuso approved these changes

2024-04-25 02:23 UTC, merged